// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface Article: NSObject
@end

@interface User: NSObject
-(IBAction) initialize:(id) id;

@end

@interface ArticleListViewController: UIViewController
-(IBAction) viewDidLoad;

@end

@interface MainViewController: UIViewController
-(IBAction) viewDidLoad;

@end

